### ISSUE TITLE
From non-pageable to pageable, the current operation will be removed when adding `operationName`

### ISSUE THREAD

**Issue by Alancere** [Azure/autorest.go#1060]
CHANGELOG:
actual:
```markdown
+	Function `*LocalRulestacksClient.ListAppIDs` has been removed
+	Function `*LocalRulestacksClient.ListCountries` has been removed
+	Function `*LocalRulestacksClient.ListPredefinedURLCategories` has been remove
```
expected:
```markdown
- Operation `*LocalRulestacksClient.ListAppIDs` has supported pagination, use `*LocalRulestacksClient.NewListAppIDsPager` instead.
- Operation `*LocalRulestacksClient.ListCountries` has supported pagination, use `*LocalRulestacksClient.NewListCountriesPager` instead.
- Operation `*LocalRulestacksClient.ListPredefinedURLCategories` has supported pagination, use `*LocalRulestacksClient.NewListPredefinedURLCategoriesPager` instead.
```

Swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/preview/2023-09-01-preview/PaloAltoNetworks.Cloudngfw.json#L3685
```yaml
        "operationId": "LocalRulestacks_listCountries",
        "description": "List of countries for Rulestack",
        ..........................................
        "x-ms-pageable": {
          "nextLinkName": "nextLink",
          "operationName": "LocalRulestacks_listCountries"
        }
```
