### ISSUE TITLE
[bug] Using an enum variable in server URL leads to uncompilable code

### ISSUE THREAD

**Issue by anlandu** [Azure/autorest.go#1184]
I have an openapi 3 spec with the following servers:
```
servers:
  - url: https://{environment}
    variables:
      environment:
        default: a.net   
        enum:
          - a.net
          - b.net
```

Autorest generates the following 
`host = strings.ReplaceAll(host, "{environment}", *options.Environment)`
where Environment is of type *Environment, which has underlying type string. This leads to a compilation error as the variable needs to be cast down to a string before being passed:
`cannot use *options.Environment (variable of type Environment) as string value in argument to strings.ReplaceAll`
Let me know if I'm missing any useful information or if my understanding is off. Thank you!
