### ISSUE TITLE
Parsing comments strips things that look like HTML elements

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest.go#623]
In `transform.ts:parseComments()`, the conversion to HTML then text can strip some content that appears to be HTML tags.

E.g. in additionalProperties.json in the test server, the description "Dictionary of <any>" is munged into "Dictionary of ".

**Comment by chamons** [comment]
I'm not sure that this is due to comment HTML parsing. If I dump the code-mode-v4.yaml I see:

```yaml
      language:
        default:
          name: PetAPTrue
          description: Dictionary of <any>
        go:
          name: PetAPTrue
          description: Dictionary of
          elementIsPtr: false
          marshallingFormat: json
```

where Go's description is cut off.

**Comment by chamons** [comment]
If I run this against C#, the yaml contains:

```
      language: !Languages 
        default:
          name: PetAPTrue
          description: Dictionary of <any>
```
