### ISSUE TITLE
testgen could not handle non-string variable and step variable in api scenario correctly

### ISSUE THREAD

**Issue by tadelesh** [Azure/autorest.go#890]
Example:
```
scope: ResourceGroup

variables:
  globalLocation: Global
  publicPort:
    type: int
    value: 6910

scenarios:
  - scenario: SignalR
    description: Microsoft.SignalRService/Basic_CRUD
    steps:
      - step: SignalR_CreateOrUpdate
        exampleFile: ../examples/SignalR_CreateOrUpdate.json
        requestUpdate:
          - replace: /parameters/properties/publicPort
            value: $(publicPort)
          - replace: /parameters/location
            value: $(location)-test1
        variables:
          location: $(globalLocation)-test2
        outputVariables:
          signalRId:
            fromResponse: /id
```
