### ISSUE TITLE
Support arm-id formatted strings (and x-ms-arm-id-details)

### ISSUE THREAD

**Issue by serbrech** [Azure/autorest.go#914]
readme used (latest everything) :

```yaml
version: 3.9.4
go: true
track2: true
debug: true
input-file:
- ...
file-prefix: zz_generated_
azure-arm: true
module-version: 0.0.1
use-extension:
  "@autorest/modelerfour": "~4.26.0"
  "@autorest/go": "4.0.0-preview.45"
```

https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-arm-id-details

current failure: 
```
fatal   | YAMLException: unknown tag !<!ArmIdSchema> in "code-model-v4.yaml" (723:3)

 720 |           name: ClusterResourceId
 721 |           description: A type def ...
 722 |       protocol: !Protocols {}
 723 |   byteArrays:
```

this is documented and supported in cadl Azure package via  [Azure.ResourceManager.ResourceIdentifier](https://azure.github.io/cadl-azure/docs/libraries/azure-resource-manager/reference/data-types#Azure.ResourceManager.ResourceIdentifierAllowedResource])

usage :

```
scalar ClusterResourceId
  extends Azure.ResourceManager.ResourceIdentifier<[
    {
      type: "Microsoft.ContainerService/managedClusters",
    }
  ]>;

```

which generates : 

```json
"definitions": {
    "ClusterResourceId": {
      "type": "string",
      "description": "A type definition that refers the id to an ARM resource.",
      "format": "arm-id",
      "x-ms-arm-id-details": {
        "allowedResources": [
          {
            "type": "Microsoft.ContainerService/managedClusters"
          }
        ]
      }
    }
  }
```
